import { ILanguage } from "../model/language/language";
import { IPiercing } from "../model/piercing/piercing";
import { IBreastSize } from "./breastSize";
import { IBreastType } from "./breastType";
import { ICity } from "./city";
import { ICountry } from "./country";
import { ICurrency } from "./currency";
import { IDayOfWeek } from "./dayOfWeek";
import { IDistrict } from "./district";
import { IEthnicGroup } from "./ethnicGroup";
import { IEyesColor } from "./eyesColor";
import { IHairColor } from "./hairColor";
import { IHairSize } from "./hairSize";
import { IMeeting } from "./meeting";
import { IMeetingPlace } from "./meetingPlace";
import { IModelType } from "./modelType";
import { INationality } from "./nationality";
import { IOrientation } from "./orientation";
import { IProposalPlace } from "./proposalPlace";
import { IPubisHair } from "./pubisHair";
import { IServiceCategory } from "./serviceCategory";
import { ISiteLanguage } from "./siteLanguage";
import { ISmooker } from "./smooker";
import { ITatoo } from "./tatoo";
import { ITrip } from "./trip";
import { IUnderground } from "./underground";
import { IWorkDuration } from "./workDuration";

export interface IGeneral {
    site_languages: ISiteLanguage[];
    countries: ICountry[];
    cities: number[];
    districts: IDistrict[];
    undergrounds: IUnderground[];
    model_types: IModelType[];
    orientations: IOrientation[];
    meetings: IMeeting[];
    meeting_places: IMeetingPlace[];
    ethnic_groups: IEthnicGroup[];
    hair_colors: IHairColor[];
    hair_sizes: IHairSize[];
    pubis_hairs: IPubisHair[];
    breast_sizes: IBreastSize[];
    breast_types: IBreastType[];
    nationalities: INationality[];
    trips: ITrip[];
    languages: ILanguage[];
    tatoos: ITatoo[];
    smookers: ISmooker[];
    eyes_colors: IEyesColor[];
    currencies: ICurrency[];
    work_durations: IWorkDuration[];
    days_of_week: IDayOfWeek[];
    service_categories: IServiceCategory[];
    piercings: IPiercing[];
    proposal_places: IProposalPlace[];
}